### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by aicynide** [sharkiller/Reproductor-MPD-M3U8#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sharkiller** [comment]
There is no public source code. The extension is not obfuscated but is simplified to prevent clones with malware that some sites started to distribute on previous versions.
