### ISSUE TITLE
Add support for HTTP MPEG-TS streams

### ISSUE THREAD

**Issue by lars18th** [sharkiller/Reproductor-MPD-M3U8#12]
**Is your feature request related to a problem? Please describe.**
I'm using SAT>IP M3U lists for my local DVB-S2 tuners. The server provides simple `http://satipserver.local/channel.ts` links inside the M3U. And I can download the M3U and see all the channels and the EPG. However, I can't play the channel because at time only HLS (and similar protocols) is supported. The same M3U can be opened and played using the common VLC player.

**Describe the solution you'd like**
Add support for the simple MPEG-TS over continous HTTP streaming.

**Describe alternatives you've considered**
No alternatives available.

**Additional context**
This will be useful only for local streaming.

Thank you!

**Comment by sharkiller** [comment]
are you sure the server doesnt provide a m3u8 or mpd link? i dont have any link like that to test if it works currently.  
Also some direct sat channels use codecs not supported by chrome.

**Comment by lars18th** [comment]
> are you sure the server doesnt provide a m3u8 or mpd link?

Yes. SAT>IP servers only provide RTSP (difficult to implement in this project) and HTTP streaming of MPEG-TS streams.

> i dont have any link like that to test if it works currently.

If you put _any_ MPEG-TS inside one HTTP server, then you have it. It's the same as HLS streams with MPEG-TS encapsulation using only  one chunk file and without any manifest file.
You can use for example the streams from here: https://testfile.org/videos/ts/
Check them openning using VLC: https://testfileorg.netwet.net/Sample%20Video%202/sample_1280x720.ts
Any DVB capture stream in MPEG-TS could be used.

> Also some direct sat channels use codecs not supported by chrome.

This is not a problem. Some channels are regular H.264 video with MP2 or AAC audio.

I hope you will want to add support.
Regards.
