### ISSUE TITLE
get the previous versions of this application?

### ISSUE THREAD

**Issue by audiopsicotiko** [sharkiller/Reproductor-MPD-M3U8#3]
hello. Is there any way to get the previous versions of this application?
since the last version is not working correctly for me.
error: it does not load the playlists, before it did.
In addition, some mpd channels do not work correctly (channels working in another chrome extension, and that in previous versions of this extension worked the same before.

**Comment by sharkiller** [comment]
@audiopsicotiko @wiormax can you share the errors you get on the console?

**Comment by wiormax** [comment]
> @audiopsicotiko @wiormax can you share the errors you get on the console?
> 
> If you want to contact in private you can DM at discord: https://discordapp.com/users/132582359131357184

no any errors just testing same playlist that i use in ott but in this addon dont load the playlist just blackscreen nothing happen as @audiopsicotiko comment.

regards

**Comment by sharkiller** [comment]
@wiormax can you share a sample? i test with multiple playlist and they load just fine. 

in the network tab it try to even load the playlist?

**Comment by wiormax** [comment]
i tried everything in console log i can see that playlist is loaded but just black screen only work with hls and single url in tab.

regards

**Comment by sharkiller** [comment]
@wiormax but you need to give me any hint. just a "doesnt work" doesnt help. 

what are you trying to play? mpd, m3u8? clearkey? widevine? are you using direct link with parameters or the iptv list? if its the m3u player it generate the list of channels in the left?

**Comment by wiormax** [comment]
Versión 116.0.5845.111 (Build oficial) (64 bits)

testing with same ott playlist format with clearkeys i was reading your support and is the same playlist format.

regards

**Comment by sharkiller** [comment]
@wiormax you understand that the info you are providing me doesnt help? 
doesnt matter if it works in another player because m3u is not standard and you could have something in the list that is breaking the parser.

this even run for you?
chrome-extension://opmeopcambhfimffbomjgemehjkbbmji/iptv/player.html#https://github.com/sharkiller/Reproductor-MPD-M3U8/raw/main/test.m3u

**Comment by wiormax** [comment]
running so my ott format list doesnt work with this app

thanks

**Comment by sharkiller** [comment]
@wiormax sorry if you can't provide proper report i cant help you. i cant do anything with "my list".

**Comment by wiormax** [comment]
this is the format that i use

#EXTINF:-1 chanel name
#EXTINF:-1 tvg-id="guide"
#EXTINF:-1 tvg-logo="http://logo.com"
#EXTINF:-1 group-title="sports"
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=clearkey
#KODIPROP:inputstream.adaptive.license_key={"keys": [{"kty": "oct","k": "xxxxxxxxxxxxxxxx","kid": "xxxxxxxxxxxxxxxx"}],"type": "temporary"}
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
https://manifest.mpd

thanks

**Comment by sharkiller** [comment]
@wiormax I see some errors 

* #EXTINF should be 1 line, not multiple.
* In my parser i use file_type instead manifest_type. i going to add both for next version. also you only need that line if the link doesnt end in mpd or m3u8.
* I dont support #EXTVLCOPT: for headers. you should use #KODIPROP:


A proper channel should be like this:

``` 
#KODIPROP:inputstream.adaptive.file_type=mpd
#KODIPROP:inputstream.adaptive.license_type=clearkey
#KODIPROP:inputstream.adaptive.license_key={"keys": [{"kty": "oct","k": "xxxxxxxxxxxxxxxx","kid": "xxxxxxxxxxxxxxxx"}],"type": "temporary"}
#KODIPROP:inputstream.adaptive.stream_headers=user-agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
#EXTINF:-1 tvg-id="guide" tvg-logo="http://logo.com/" group-title="sports", Chanel name
https://manifest.mpd/
```

**Comment by wiormax** [comment]
ok got it thanks

**Comment by audiopsicotiko** [comment]
I have reinstalled version 8.26.2.30129 with the same list and it works perfectly. (I had it saved on another pc)
but in the latest version 8.27.1.30818 it only remains on a black screen.
I'm sorry I'm not a specialist, I don't know how to analyze the console. so I can't help on that.
but I don't think it's a problem on my list. because in v8.26 it works fine.
An example from my list would be:

#EXTM3U list-name="Canales" list-image="https://xxxx/logo.png"

#KODIPROP:inputstream.adaptive.stream_headers=User-Agent="Mozilla/5.0 (Windows NT 11.O; Win64; x64) AppleWebKit/537.36 (KHTML, like Geck0) Chrome/102.0.0.0 Safari/537.37"
#EXTINF:-1 tvg-logo="https://i.ibb.co/71LY9Sq/tntsports.png" group-title="DEPORTES", TNT Sport cl
#KODIPROP:inputstream.adaptive.license_type=clearkey
#KODIPROP:inputstream.adaptive.license_key=xxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxx
https://xxxxx.xxx.net/live_xxxx/manifest.mpd

**Comment by sharkiller** [comment]
@audiopsicotiko  @wiormax 
a new version is out with a lot a fixes. check if works.
also now there is a converter in the extension that help you create the m3u block for the channels with the proper format.

**Comment by audiopsicotiko** [comment]
Confirmed. The new update fixed any problem.
good job and thank you very much.
