### ISSUE TITLE
Old version chrome 96 compatible

### ISSUE THREAD

**Issue by 0hitech85** [sharkiller/Reproductor-MPD-M3U8#6]
Hi

it is possible to have an old version of your addon (crx or zip is the same)? i have an android 5.1 tablet with kiwi (chromium based) browser 96, can't update more than that version anymore

thanks in advance

**Comment by sharkiller** [comment]
@0hitech85 the extension if i remember correctly it use some new javascripts apis that are not available on versions lower than 100. Like to decompress gzip epgs.   

Here is the latest version without the `"minimum_chrome_version": "100",`  in the manifest.  
But if you have any problem with it I cant remove functionalities to support your outdated system.

[mpd-player-8.27.1.30928_nolimitversion.zip](https://github.com/sharkiller/Reproductor-MPD-M3U8/files/12885912/mpd-player-8.27.1.30928_nolimitversion.zip)

**Comment by 0hitech85** [comment]
Thanks for the upload, it allowed me to install, but didn't work, thanks anyway
