### ISSUE TITLE
the m3u file "invalid playlist"

### ISSUE THREAD

**Issue by ibnusaja** [sharkiller/Reproductor-MPD-M3U8#7]
```
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.stream_headers=referer=https://www.visionplus.id/
#KODIPROP:inputstream.adaptive.license_key=https://mrpw.ptmnc01.verspective.net/?deviceId=NDIzMDJhZmUtYWRjMi0zNGJkLTkyN2EtYmE1ZDFlZWIwODEz
#EXTINF:-1 tvg-id="ttvNMoviesAsia.hk" tvg-url="https://raw.githubusercontent.com/hendroagung2904/JejeVisionEpg/main/JejeVisionEpg.xml" tvg-logo="https://www.mncvision.id/userfiles/image/channel/channel_25.png" group-title="Korean Channels",TvN movies HD
https://nyanv-live-cdn.mncnow.id/live/eds/tvNMovies/sa_dash_v
![bandicam 2023-10-13 17-59-33-332](https://github.com/sharkiller/Reproductor-MPD-M3U8/assets/45093115/1c419691-62e6-4197-8d5e-47db74b2bdc0)
mx/tvNMovies.mpd
```

This is the code that should already be in accordance with the tutorial in your repository's documentation. However, why is it that this link (which I have saved in a file) cannot be opened using your application (extension)?

Thank you.

**Comment by ibnusaja** [comment]
![bandicam 2023-10-13 17-59-33-332](https://github.com/sharkiller/Reproductor-MPD-M3U8/assets/45093115/3c2b8910-a3c4-4e7d-b31f-26ac5a207c69)

**Comment by sharkiller** [comment]
You are using wrong format. The first line of a m3u list should always be `#EXTM3U` 

https://github.com/sharkiller/Reproductor-MPD-M3U8/wiki/M3U-format

**Comment by ibnusaja** [comment]
@sharkiller thanks for answer, now my chrome is work for play the m3u link.
