### ISSUE TITLE
m3u playlist does not work embed on my page 

### ISSUE THREAD

**Issue by imrsaleh** [sharkiller/Reproductor-MPD-M3U8#9]
m3u playlist does not work on my page

<iframe src="chrome-extension://opmeopcambhfimffbomjgemehjkbbmji/iptv/player.html#https://iptv-org.github.io/iptv/categories/animation.m3u" width="1280" height="720"></iframe>

**Screenshots**
![1](https://github.com/sharkiller/Reproductor-MPD-M3U8/assets/119083621/947829e5-fa4d-4394-add3-a7be691a98ce)

 - OS: [windows 11 64bit]
 - Browser [Brave, Microsoft Edge]
 - Version [last]

**Comment by sharkiller** [comment]
@imrsaleh your example works just fine. if you use a custom playlist remember to follow how to properly configure the channels to work. like custom headers if needed. Also maybe you are using channels that use a codec that chrome doesnt support.  
That error mean:
> Either an empty playlist was requested or none of the items passed our filter for valid files. This includes the browser being unable to play the video, e.g. if the required codecs are not installed.
